//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteProducts.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuceneSearchRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuceneSearchRepository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WasteProducts.DataAccess.Resources.LuceneSearchRepository", typeof(LuceneSearchRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t clear index..
        /// </summary>
        internal static string ClearIndexError {
            get {
                return ResourceManager.GetString("ClearIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сan&apos;t delete entity with empty id..
        /// </summary>
        internal static string DeleteWithEmptyIdError {
            get {
                return ResourceManager.GetString("DeleteWithEmptyIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t search within empty filelds..
        /// </summary>
        internal static string EmptyFieldsError {
            get {
                return ResourceManager.GetString("EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open Lucene index..
        /// </summary>
        internal static string IndexOpenError {
            get {
                return ResourceManager.GetString("IndexOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find Lucene index storage path settings..
        /// </summary>
        internal static string IndexPathNotFound {
            get {
                return ResourceManager.GetString("IndexPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t optimize index..
        /// </summary>
        internal static string OptimizeIndexError {
            get {
                return ResourceManager.GetString("OptimizeIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t proceed query..
        /// </summary>
        internal static string ProcessQueryError {
            get {
                return ResourceManager.GetString("ProcessQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search string can&apos;t be empty or null or consist only from whitespaces.
        /// </summary>
        internal static string QueryStrError {
            get {
                return ResourceManager.GetString("QueryStrError", resourceCulture);
            }
        }
    }
}
